Objective: Create a visualization showing electricity production and consumption wrt renewable and non-renewable sources

In [1]:
import pandas as pd

In [2]:
data_df = pd.read_csv('../Datasets/energy_data_unclean.csv')

In [3]:
data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17239 entries, 0 to 17238
Columns: 128 entries, iso_code to wind_energy_per_capita
dtypes: float64(125), int64(1), object(2)
memory usage: 16.8+ MB

In [4]:
print(list(data_df.columns))

['iso_code', 'country', 'year', 'coal_prod_change_pct', 'coal_prod_change_twh', 'gas_prod_change_pct', 'gas_prod_change_twh', 'oil_prod_change_pct', 'oil_prod_change_twh', 'energy_cons_change_pct', 'energy_cons_change_twh', 'biofuel_share_elec', 'biofuel_elec_per_capita', 'biofuel_cons_change_pct', 'biofuel_share_energy', 'biofuel_cons_change_twh', 'biofuel_consumption', 'biofuel_cons_per_capita', 'carbon_intensity_elec', 'coal_share_elec', 'coal_cons_change_pct', 'coal_share_energy', 'coal_cons_change_twh', 'coal_consumption', 'coal_elec_per_capita', 'coal_cons_per_capita', 'coal_production', 'coal_prod_per_capita', 'electricity_demand', 'biofuel_electricity', 'coal_electricity', 'fossil_electricity', 'gas_electricity', 'hydro_electricity', 'nuclear_electricity', 'oil_electricity', 'other_renewable_exc_biofuel_electricity', 'other_renewable_electricity', 'renewables_electricity', 'solar_electricity', 'wind_electricity', 'electricity_generation', 'greenhouse_gas_emissions', 'energy_per_gdp', 'energy_per_capita', 'fossil_cons_change_pct', 'fossil_share_energy', 'fossil_cons_change_twh', 'fossil_fuel_consumption', 'fossil_energy_per_capita', 'fossil_cons_per_capita', 'fossil_share_elec', 'gdp', 'gas_share_elec', 'gas_cons_change_pct', 'gas_share_energy', 'gas_cons_change_twh', 'gas_consumption', 'gas_elec_per_capita', 'gas_energy_per_capita', 'gas_production', 'gas_prod_per_capita', 'hydro_share_elec', 'hydro_cons_change_pct', 'hydro_share_energy', 'hydro_cons_change_twh', 'hydro_consumption', 'hydro_elec_per_capita', 'hydro_energy_per_capita', 'low_carbon_share_elec', 'low_carbon_electricity', 'low_carbon_elec_per_capita', 'low_carbon_cons_change_pct', 'low_carbon_share_energy', 'low_carbon_cons_change_twh', 'low_carbon_consumption', 'low_carbon_energy_per_capita', 'net_elec_imports_share_demand', 'net_elec_imports', 'nuclear_share_elec', 'nuclear_cons_change_pct', 'nuclear_share_energy', 'nuclear_cons_change_twh', 'nuclear_consumption', 'nuclear_elec_per_capita', 'nuclear_energy_per_capita', 'oil_share_elec', 'oil_cons_change_pct', 'oil_share_energy', 'oil_cons_change_twh', 'oil_consumption', 'oil_elec_per_capita', 'oil_energy_per_capita', 'oil_production', 'oil_prod_per_capita', 'other_renewables_elec_per_capita_exc_biofuel', 'other_renewables_elec_per_capita', 'other_renewables_cons_change_pct', 'other_renewables_share_energy', 'other_renewables_cons_change_twh', 'other_renewable_consumption', 'other_renewables_share_elec_exc_biofuel', 'other_renewables_share_elec', 'other_renewables_energy_per_capita', 'per_capita_electricity', 'population', 'primary_energy_consumption', 'renewables_elec_per_capita', 'renewables_share_elec', 'renewables_cons_change_pct', 'renewables_share_energy', 'renewables_cons_change_twh', 'renewables_consumption', 'renewables_energy_per_capita', 'solar_share_elec', 'solar_cons_change_pct', 'solar_share_energy', 'solar_cons_change_twh', 'solar_consumption', 'solar_elec_per_capita', 'solar_energy_per_capita', 'wind_share_elec', 'wind_cons_change_pct', 'wind_share_energy', 'wind_cons_change_twh', 'wind_consumption', 'wind_elec_per_capita', 'wind_energy_per_capita']

In [5]:
year_to_drop = list(data_df[data_df['year'] < 2001].year.unique())

data_df = data_df.drop(data_df[data_df.year.isin(year_to_drop)].index)

In [6]:
data_df.year.unique()

array([2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011,
       2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021],
      dtype=int64)

In [7]:
print(list(data_df.country.unique()))

['Afghanistan', 'Africa', 'Albania', 'Algeria', 'American Samoa', 'Angola', 'Antarctica', 'Antigua and Barbuda', 'Argentina', 'Armenia', 'Aruba', 'Asia Pacific', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bermuda', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'British Virgin Islands', 'Brunei', 'Bulgaria', 'Burkina Faso', 'Burundi', 'CIS', 'Cambodia', 'Cameroon', 'Canada', 'Cape Verde', 'Cayman Islands', 'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo', 'Cook Islands', 'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cuba', 'Cyprus', 'Czechia', 'Democratic Republic of Congo', 'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic', 'Eastern Africa', 'Ecuador', 'Egypt', 'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia', 'Eswatini', 'Ethiopia', 'Europe', 'European Union (27)', 'Faeroe Islands', 'Falkland Islands', 'Fiji', 'Finland', 'France', 'French Guiana', 'French Polynesia', 'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana', 'Greece', 'Greenland', 'Grenada', 'Guadeloupe', 'Guam', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras', 'Hong Kong', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', 'Kosovo', 'Kuwait', 'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Lithuania', 'Luxembourg', 'Macao', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Martinique', 'Mauritania', 'Mauritius', 'Mexico', 'Micronesia (country)', 'Middle Africa', 'Middle East', 'Moldova', 'Mongolia', 'Montenegro', 'Montserrat', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nauru', 'Nepal', 'Netherlands', 'Netherlands Antilles', 'New Caledonia', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'Niue', 'Non-OECD', 'North Korea', 'North Macedonia', 'Northern Mariana Islands', 'Norway', 'OECD', 'Oman', 'Pakistan', 'Palestine', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal', 'Puerto Rico', 'Qatar', 'Reunion', 'Romania', 'Russia', 'Rwanda', 'Saint Helena', 'Saint Kitts and Nevis', 'Saint Lucia', 'Saint Pierre and Miquelon', 'Saint Vincent and the Grenadines', 'Samoa', 'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia', 'Serbia and Montenegro', 'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia', 'Solomon Islands', 'Somalia', 'South Africa', 'South Korea', 'South Sudan', 'Spain', 'Sri Lanka', 'Sudan', 'Suriname', 'Sweden', 'Switzerland', 'Syria', 'Taiwan', 'Tajikistan', 'Tanzania', 'Thailand', 'Timor', 'Togo', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan', 'Turks and Caicos Islands', 'Tuvalu', 'U.S. Pacific Islands', 'U.S. Territories', 'USSR', 'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom', 'United States', 'United States Virgin Islands', 'Uruguay', 'Uzbekistan', 'Vanuatu', 'Venezuela', 'Vietnam', 'Wake Island', 'Western Africa', 'Western Sahara', 'World', 'Yemen', 'Zambia', 'Zimbabwe']

In [8]:
groupings = ['Africa', 'Antarctica','Asia Pacific', 'CIS','Eastern Africa', 'Europe','European Union (27)','Middle Africa','Middle East','Non-OECD','OECD','Western Africa','Western Sahara']

dependent_territories = ['American Samoa', 'Aruba', 'Bermuda', 'British Virgin Islands', 'Cayman Islands', 'Cook Islands', 'Faeroe Islands', 'Falkland Islands', 'French Guiana',
'French Polynesia', 'Greenland', 'Guadeloupe', 'Guam', 'Hong Kong', 'Macao', 'Martinique', 'Netherlands Antilles', 'New Caledonia', 'Niue', 'Northern Mariana Islands', 'Puerto Rico',
'Reunion', 'Saint Helena', 'Saint Pierre and Miquelon', 'Turks and Caicos Islands', 'United States Virgin Islands', 'U.S. Territories', 'U.S. Pacific Islands', 'Wake Island']

former_countries = ['USSR', 'Serbia and Montenegro']

In [9]:
to_remove = dependent_territories + groupings + former_countries
data_df = data_df.drop(data_df[data_df.country.isin(to_remove)].index)

#data_df = data_df.drop(data_df[data_df['country'].str.contains('Islands')].index)
#data_df = data_df.drop(data_df[data_df.country == 'Netherlands Antilles'].index)

In [10]:
list_of_country = list(data_df.country.unique())
print(list_of_country,len(list_of_country))

['Afghanistan', 'Albania', 'Algeria', 'Angola', 'Antigua and Barbuda', 'Argentina', 'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'Brunei', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia', 'Cameroon', 'Canada', 'Cape Verde', 'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo', 'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cuba', 'Cyprus', 'Czechia', 'Democratic Republic of Congo', 'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt', 'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia', 'Eswatini', 'Ethiopia', 'Fiji', 'Finland', 'France', 'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana', 'Greece', 'Grenada', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', 'Kosovo', 'Kuwait', 'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Lithuania', 'Luxembourg', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Mauritania', 'Mauritius', 'Mexico', 'Micronesia (country)', 'Moldova', 'Mongolia', 'Montenegro', 'Montserrat', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nauru', 'Nepal', 'Netherlands', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'North Korea', 'North Macedonia', 'Norway', 'Oman', 'Pakistan', 'Palestine', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal', 'Qatar', 'Romania', 'Russia', 'Rwanda', 'Saint Kitts and Nevis', 'Saint Lucia', 'Saint Vincent and the Grenadines', 'Samoa', 'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia', 'Solomon Islands', 'Somalia', 'South Africa', 'South Korea', 'South Sudan', 'Spain', 'Sri Lanka', 'Sudan', 'Suriname', 'Sweden', 'Switzerland', 'Syria', 'Taiwan', 'Tajikistan', 'Tanzania', 'Thailand', 'Timor', 'Togo', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan', 'Tuvalu', 'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom', 'United States', 'Uruguay', 'Uzbekistan', 'Vanuatu', 'Venezuela', 'Vietnam', 'World', 'Yemen', 'Zambia', 'Zimbabwe'] 192

In [11]:
missing_country = ['Andorra','Holy See','Liechtenstein','Palau','San Marino']

In [12]:
data_df.head(20)

,iso_code,country,year,coal_prod_change_pct,coal_prod_change_twh,gas_prod_change_pct,gas_prod_change_twh,oil_prod_change_pct,oil_prod_change_twh,energy_cons_change_pct,...,solar_consumption,solar_elec_per_capita,solar_energy_per_capita,wind_share_elec,wind_cons_change_pct,wind_share_energy,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_energy_per_capita
101,AFG,Afghanistan,2001,2498.993,0.145,NaN,NaN,NaN,NaN,-21.130,...,NaN,0.000,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN
102,AFG,Afghanistan,2002,-19.231,-0.029,NaN,NaN,NaN,NaN,-5.058,...,NaN,0.000,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN
103,AFG,Afghanistan,2003,66.667,0.081,NaN,NaN,NaN,NaN,17.603,...,NaN,0.000,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN
104,AFG,Afghanistan,2004,-2.857,-0.006,NaN,NaN,NaN,NaN,-7.629,...,NaN,0.000,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN
105,AFG,Afghanistan,2005,-2.941,-0.006,NaN,NaN,NaN,NaN,27.918,...,NaN,0.000,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN
106,AFG,Afghanistan,2006,6.061,0.012,NaN,NaN,NaN,NaN,25.873,...,NaN,0.000,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN
107,AFG,Afghanistan,2007,594.286,1.208,NaN,NaN,NaN,NaN,29.614,...,NaN,0.000,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN
108,AFG,Afghanistan,2008,42.798,0.604,NaN,NaN,NaN,NaN,70.857,...,NaN,0.000,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN
109,AFG,Afghanistan,2009,44.092,0.888,NaN,NaN,NaN,NaN,62.916,...,NaN,0.000,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN
110,AFG,Afghanistan,2010,45.000,1.306,NaN,NaN,NaN,NaN,24.321,...,NaN,0.000,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN
111,AFG,Afghanistan,2011,104.138,4.383,NaN,NaN,NaN,NaN,35.864,...,NaN,0.000,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN
112,AFG,Afghanistan,2012,-16.216,-1.393,NaN,NaN,NaN,NaN,-8.347,...,NaN,0.963,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN
113,AFG,Afghanistan,2013,8.629,0.621,NaN,NaN,NaN,NaN,-15.652,...,NaN,0.930,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN
114,AFG,Afghanistan,2014,12.650,0.989,NaN,NaN,NaN,NaN,-8.185,...,NaN,0.899,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN
115,AFG,Afghanistan,2015,-10.043,-0.885,NaN,NaN,NaN,NaN,10.477,...,NaN,0.872,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN
116,AFG,Afghanistan,2016,24.396,1.933,NaN,NaN,NaN,NaN,-6.900,...,NaN,1.130,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN
117,AFG,Afghanistan,2017,NaN,NaN,NaN,NaN,NaN,NaN,6.265,...,NaN,1.102,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN
118,AFG,Afghanistan,2018,NaN,NaN,NaN,NaN,NaN,NaN,14.672,...,NaN,1.076,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN
119,AFG,Afghanistan,2019,NaN,NaN,NaN,NaN,NaN,NaN,-14.326,...,NaN,1.051,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN
120,AFG,Afghanistan,2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.028,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN

In [13]:
gdp_df = pd.DataFrame(data_df.groupby('country')['gdp'].mean())

In [14]:
gdp_df.gdp.dtype

dtype('float64')

In [15]:
useful_col = ['country', 'year', 'electricity_demand', 'electricity_generation', 'coal_electricity', 'fossil_electricity',
'gas_electricity', 'oil_electricity', 'nuclear_electricity', 'biofuel_electricity', 'hydro_electricity', 'solar_electricity', 'wind_electricity', 
'greenhouse_gas_emissions']

cleaned_data = data_df[useful_col]

In [16]:
cleaned_data[cleaned_data.country == 'India']

,country,year,electricity_demand,electricity_generation,coal_electricity,fossil_electricity,gas_electricity,oil_electricity,nuclear_electricity,biofuel_electricity,hydro_electricity,solar_electricity,wind_electricity,greenhouse_gas_emissions
7353,India,2001,587.36,586.09,408.29,491.01,55.93,26.79,18.89,2.07,72.02,0.01,2.09,383.42
7354,India,2002,610.99,609.64,426.70,517.51,62.88,27.93,19.35,2.14,68.54,0.01,2.09,402.63
7355,India,2003,639.82,638.13,441.47,545.36,72.80,31.09,18.14,2.71,69.30,0.02,2.60,421.97
7356,India,2004,700.02,698.32,463.01,567.86,76.58,28.27,21.26,3.31,100.64,0.02,5.23,440.48
7357,India,2005,706.07,704.52,478.48,579.32,75.47,25.37,17.73,4.04,97.42,0.02,5.99,450.64
7358,India,2006,747.17,744.43,505.46,599.24,74.70,19.08,17.63,5.59,112.62,0.01,9.34,468.74
7359,India,2007,801.20,796.26,533.27,636.68,90.05,13.36,17.83,7.40,122.61,0.06,11.68,495.73
7360,India,2008,833.92,828.41,573.12,674.27,85.88,15.27,15.23,9.30,115.17,0.06,14.38,527.97
7361,India,2009,885.01,879.71,611.11,728.56,104.37,13.08,16.82,11.64,106.34,0.08,16.27,567.02
7362,India,2010,943.02,937.47,642.97,771.78,118.03,10.78,23.08,14.30,108.74,0.11,19.46,599.02
7363,India,2011,1039.12,1034.00,701.25,828.16,117.56,9.35,32.22,17.14,131.70,0.83,23.95,646.97
7364,India,2012,1096.48,1091.84,787.13,893.45,96.25,10.07,33.14,19.94,115.78,2.10,27.43,707.83
7365,India,2013,1150.09,1146.14,847.97,924.93,66.31,10.65,33.31,22.48,131.98,3.43,30.01,744.52
7366,India,2014,1262.59,1262.02,949.93,1025.29,64.01,11.35,34.69,24.68,139.00,4.91,33.45,828.30
7367,India,2015,1317.25,1317.16,1006.55,1080.44,64.77,9.12,38.31,25.82,133.28,6.57,32.74,873.77
7368,India,2016,1400.54,1401.63,1073.60,1155.52,72.62,9.30,37.90,24.82,128.38,11.56,43.45,932.71
7369,India,2017,1469.56,1471.15,1115.24,1198.85,74.99,8.62,37.41,24.91,135.82,21.54,52.62,968.33
7370,India,2018,1575.14,1578.98,1198.86,1276.32,71.26,6.20,39.05,27.22,139.75,36.33,60.31,1034.81
7371,India,2019,1599.78,1603.48,1184.53,1257.05,67.47,5.05,45.16,29.67,162.02,46.27,63.31,1022.08
7372,India,2020,1561.18,1560.33,1125.22,1200.87,70.79,4.86,44.61,32.10,163.64,58.68,60.43,976.10
7373,India,2021,1695.74,1696.80,1250.46,1313.43,58.11,4.86,42.67,33.01,171.27,68.34,68.08,1073.49

In [17]:
cleaned_data.isnull().sum()

country                      0
year                         0
electricity_demand          55
electricity_generation      55
coal_electricity            55
fossil_electricity          55
gas_electricity             55
oil_electricity             55
nuclear_electricity         55
biofuel_electricity         55
hydro_electricity           55
solar_electricity           55
wind_electricity            55
greenhouse_gas_emissions    55
dtype: int64

In [18]:
cleaned_data[cleaned_data.gas_electricity.isnull()]

,country,year,electricity_demand,electricity_generation,coal_electricity,fossil_electricity,gas_electricity,oil_electricity,nuclear_electricity,biofuel_electricity,hydro_electricity,solar_electricity,wind_electricity,greenhouse_gas_emissions
9727,Micronesia (country),2001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9728,Micronesia (country),2002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9729,Micronesia (country),2003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9730,Micronesia (country),2004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9731,Micronesia (country),2005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9732,Micronesia (country),2006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9733,Micronesia (country),2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9734,Micronesia (country),2008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9735,Micronesia (country),2009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9736,Micronesia (country),2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9737,Micronesia (country),2011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9738,Micronesia (country),2012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9739,Micronesia (country),2013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9740,Micronesia (country),2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9741,Micronesia (country),2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9742,Micronesia (country),2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9743,Micronesia (country),2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9744,Micronesia (country),2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9745,Micronesia (country),2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15073,Timor,2003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15074,Timor,2004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15075,Timor,2005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15076,Timor,2006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15077,Timor,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15078,Timor,2008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15079,Timor,2009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15080,Timor,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15081,Timor,2011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15082,Timor,2012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15083,Timor,2013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15084,Timor,2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15085,Timor,2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15086,Timor,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15087,Timor,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15088,Timor,2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15089,Timor,2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15570,Tuvalu,2001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15571,Tuvalu,2002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15572,Tuvalu,2003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15573,Tuvalu,2004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15574,Tuvalu,2005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15575,Tuvalu,2006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15576,Tuvalu,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15577,Tuvalu,2008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15578,Tuvalu,2009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15579,Tuvalu,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15580,Tuvalu,2011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15581,Tuvalu,2012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15582,Tuvalu,2013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15583,Tuvalu,2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15584,Tuvalu,2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15585,Tuvalu,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15586,Tuvalu,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15587,Tuvalu,2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15588,Tuvalu,2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
#dropping country with no data

to_remove = list(cleaned_data[cleaned_data.gas_electricity.isnull()].country.unique())
cleaned_data = cleaned_data.drop(cleaned_data[cleaned_data.country.isin(to_remove)].index)

In [20]:
cleaned_data.isnull().sum()

country                     0
year                        0
electricity_demand          0
electricity_generation      0
coal_electricity            0
fossil_electricity          0
gas_electricity             0
oil_electricity             0
nuclear_electricity         0
biofuel_electricity         0
hydro_electricity           0
solar_electricity           0
wind_electricity            0
greenhouse_gas_emissions    0
dtype: int64

In [21]:
cleaned_data = cleaned_data.reset_index(drop=True)
cleaned_data.head(50)

,country,year,electricity_demand,electricity_generation,coal_electricity,fossil_electricity,gas_electricity,oil_electricity,nuclear_electricity,biofuel_electricity,hydro_electricity,solar_electricity,wind_electricity,greenhouse_gas_emissions
0,Afghanistan,2001,0.69,0.59,0.0,0.09,0.00,0.09,0.0,0.0,0.50,0.00,0.0,0.07
1,Afghanistan,2002,0.79,0.69,0.0,0.13,0.00,0.13,0.0,0.0,0.56,0.00,0.0,0.10
2,Afghanistan,2003,1.04,0.94,0.0,0.31,0.00,0.31,0.0,0.0,0.63,0.00,0.0,0.24
3,Afghanistan,2004,0.99,0.89,0.0,0.33,0.00,0.33,0.0,0.0,0.56,0.00,0.0,0.24
4,Afghanistan,2005,1.03,0.93,0.0,0.34,0.00,0.34,0.0,0.0,0.59,0.00,0.0,0.25
5,Afghanistan,2006,1.27,0.84,0.0,0.20,0.00,0.20,0.0,0.0,0.64,0.00,0.0,0.16
6,Afghanistan,2007,1.56,0.95,0.0,0.20,0.00,0.20,0.0,0.0,0.75,0.00,0.0,0.16
7,Afghanistan,2008,1.48,0.73,0.0,0.19,0.00,0.19,0.0,0.0,0.54,0.00,0.0,0.14
8,Afghanistan,2009,2.09,0.94,0.0,0.16,0.00,0.16,0.0,0.0,0.78,0.00,0.0,0.13
9,Afghanistan,2010,2.51,0.94,0.0,0.19,0.00,0.19,0.0,0.0,0.75,0.00,0.0,0.15
10,Afghanistan,2011,3.03,0.78,0.0,0.18,0.00,0.18,0.0,0.0,0.60,0.00,0.0,0.14
11,Afghanistan,2012,3.95,0.88,0.0,0.14,0.00,0.14,0.0,0.0,0.71,0.03,0.0,0.12
12,Afghanistan,2013,4.73,1.11,0.0,0.22,0.00,0.22,0.0,0.0,0.86,0.03,0.0,0.17
13,Afghanistan,2014,4.87,1.16,0.0,0.16,0.00,0.16,0.0,0.0,0.97,0.03,0.0,0.13
14,Afghanistan,2015,4.96,1.18,0.0,0.15,0.00,0.15,0.0,0.0,1.00,0.03,0.0,0.13
15,Afghanistan,2016,5.54,1.21,0.0,0.15,0.00,0.15,0.0,0.0,1.02,0.04,0.0,0.13
16,Afghanistan,2017,5.88,1.27,0.0,0.18,0.00,0.18,0.0,0.0,1.05,0.04,0.0,0.16
17,Afghanistan,2018,6.16,1.17,0.0,0.20,0.00,0.20,0.0,0.0,0.93,0.04,0.0,0.16
18,Afghanistan,2019,5.97,1.06,0.0,0.18,0.00,0.18,0.0,0.0,0.84,0.04,0.0,0.15
19,Afghanistan,2020,5.75,0.84,0.0,0.18,0.00,0.18,0.0,0.0,0.62,0.04,0.0,0.14
20,Albania,2001,5.48,3.73,0.0,0.17,0.00,0.17,0.0,0.0,3.56,0.00,0.0,0.21
21,Albania,2002,5.85,3.74,0.0,0.23,0.00,0.23,0.0,0.0,3.51,0.00,0.0,0.24
22,Albania,2003,5.92,5.00,0.0,0.11,0.00,0.11,0.0,0.0,4.89,0.00,0.0,0.20
23,Albania,2004,6.09,5.61,0.0,0.14,0.00,0.14,0.0,0.0,5.47,0.00,0.0,0.23
24,Albania,2005,5.81,5.44,0.0,0.07,0.00,0.07,0.0,0.0,5.37,0.00,0.0,0.18
25,Albania,2006,6.13,5.52,0.0,0.09,0.00,0.09,0.0,0.0,5.43,0.00,0.0,0.19
26,Albania,2007,5.69,2.86,0.0,0.07,0.00,0.07,0.0,0.0,2.79,0.00,0.0,0.12
27,Albania,2008,6.23,3.80,0.0,0.00,0.00,0.00,0.0,0.0,3.80,0.00,0.0,0.09
28,Albania,2009,6.60,5.20,0.0,0.00,0.00,0.00,0.0,0.0,5.20,0.00,0.0,0.12
29,Albania,2010,6.62,7.57,0.0,0.00,0.00,0.00,0.0,0.0,7.57,0.00,0.0,0.18
30,Albania,2011,7.45,4.19,0.0,0.06,0.00,0.06,0.0,0.0,4.13,0.00,0.0,0.14
31,Albania,2012,7.26,4.72,0.0,0.00,0.00,0.00,0.0,0.0,4.72,0.00,0.0,0.11
32,Albania,2013,9.28,6.96,0.0,0.00,0.00,0.00,0.0,0.0,6.96,0.00,0.0,0.17
33,Albania,2014,7.79,4.72,0.0,0.00,0.00,0.00,0.0,0.0,4.72,0.00,0.0,0.11
34,Albania,2015,7.29,5.89,0.0,0.00,0.00,0.00,0.0,0.0,5.89,0.00,0.0,0.14
35,Albania,2016,7.74,7.78,0.0,0.00,0.00,0.00,0.0,0.0,7.78,0.00,0.0,0.19
36,Albania,2017,7.43,4.52,0.0,0.00,0.00,0.00,0.0,0.0,4.52,0.00,0.0,0.11
37,Albania,2018,7.64,8.55,0.0,0.00,0.00,0.00,0.0,0.0,8.55,0.00,0.0,0.21
38,Albania,2019,7.61,5.20,0.0,0.00,0.00,0.00,0.0,0.0,5.18,0.02,0.0,0.12
39,Albania,2020,7.59,5.31,0.0,0.00,0.00,0.00,0.0,0.0,5.28,0.03,0.0,0.13
40,Algeria,2001,24.98,25.03,0.0,24.96,24.96,0.00,0.0,0.0,0.07,0.00,0.0,12.23
41,Algeria,2002,25.98,26.00,0.0,25.94,25.94,0.00,0.0,0.0,0.06,0.00,0.0,12.71
42,Algeria,2003,27.82,27.81,0.0,27.55,27.55,0.00,0.0,0.0,0.26,0.00,0.0,13.51
43,Algeria,2004,29.40,29.39,0.0,29.14,29.14,0.00,0.0,0.0,0.25,0.00,0.0,14.29
44,Algeria,2005,31.99,31.91,0.0,31.36,31.36,0.00,0.0,0.0,0.55,0.00,0.0,15.38
45,Algeria,2006,33.21,33.13,0.0,32.91,32.91,0.00,0.0,0.0,0.22,0.00,0.0,16.14
46,Algeria,2007,34.98,34.97,0.0,34.75,34.75,0.00,0.0,0.0,0.22,0.00,0.0,17.04
47,Algeria,2008,37.79,37.84,0.0,37.56,37.56,0.00,0.0,0.0,0.28,0.00,0.0,18.41
48,Algeria,2009,36.17,36.20,0.0,35.90,35.90,0.00,0.0,0.0,0.30,0.00,0.0,17.60
49,Algeria,2010,42.93,43.00,0.0,42.83,42.83,0.00,0.0,0.0,0.17,0.00,0.0,20.99

In [22]:
prev_cat = list(cleaned_data.columns)

print(prev_cat)

['country', 'year', 'electricity_demand', 'electricity_generation', 'coal_electricity', 'fossil_electricity', 'gas_electricity', 'oil_electricity', 'nuclear_electricity', 'biofuel_electricity', 'hydro_electricity', 'solar_electricity', 'wind_electricity', 'greenhouse_gas_emissions']

In [23]:
new_cat = ['Country', 'Year', 'Demand (TWh)','Generation (TWh)', 'Coal (TWh)', 'Fossil (TWh)', 'Gas (TWh)', 'Oil (TWh)', 'Nuclear (TWh)','Biofuel (TWh)', 
'Hydro (TWh)', 'Solar (TWh)','Wind (TWh)', 'GHG emission (MT CO2)']

In [24]:
col = dict(zip(prev_cat,new_cat))

print(col)

{'country': 'Country', 'year': 'Year', 'electricity_demand': 'Demand (TWh)', 'electricity_generation': 'Generation (TWh)', 'coal_electricity': 'Coal (TWh)', 'fossil_electricity': 'Fossil (TWh)', 'gas_electricity': 'Gas (TWh)', 'oil_electricity': 'Oil (TWh)', 'nuclear_electricity': 'Nuclear (TWh)', 'biofuel_electricity': 'Biofuel (TWh)', 'hydro_electricity': 'Hydro (TWh)', 'solar_electricity': 'Solar (TWh)', 'wind_electricity': 'Wind (TWh)', 'greenhouse_gas_emissions': 'GHG emission (MT CO2)'}

In [25]:
cleaned_data.rename(columns = col, inplace=True)
cleaned_data.columns

Index(['Country', 'Year', 'Demand (TWh)', 'Generation (TWh)', 'Coal (TWh)',
       'Fossil (TWh)', 'Gas (TWh)', 'Oil (TWh)', 'Nuclear (TWh)',
       'Biofuel (TWh)', 'Hydro (TWh)', 'Solar (TWh)', 'Wind (TWh)',
       'GHG emission (MT CO2)'],
      dtype='object')

In [32]:
#Dropping year 2021 since, all countries don't have values for 2021

cleaned_data =  cleaned_data.drop(cleaned_data[cleaned_data.Year == 2021].index)

In [33]:
cleaned_data[cleaned_data.Country == 'India']

,Country,Year,Demand (TWh),Generation (TWh),Coal (TWh),Fossil (TWh),Gas (TWh),Oil (TWh),Nuclear (TWh),Biofuel (TWh),Hydro (TWh),Solar (TWh),Wind (TWh),GHG emission (MT CO2)
1531,India,2001,587.36,586.09,408.29,491.01,55.93,26.79,18.89,2.07,72.02,0.01,2.09,383.42
1532,India,2002,610.99,609.64,426.70,517.51,62.88,27.93,19.35,2.14,68.54,0.01,2.09,402.63
1533,India,2003,639.82,638.13,441.47,545.36,72.80,31.09,18.14,2.71,69.30,0.02,2.60,421.97
1534,India,2004,700.02,698.32,463.01,567.86,76.58,28.27,21.26,3.31,100.64,0.02,5.23,440.48
1535,India,2005,706.07,704.52,478.48,579.32,75.47,25.37,17.73,4.04,97.42,0.02,5.99,450.64
1536,India,2006,747.17,744.43,505.46,599.24,74.70,19.08,17.63,5.59,112.62,0.01,9.34,468.74
1537,India,2007,801.20,796.26,533.27,636.68,90.05,13.36,17.83,7.40,122.61,0.06,11.68,495.73
1538,India,2008,833.92,828.41,573.12,674.27,85.88,15.27,15.23,9.30,115.17,0.06,14.38,527.97
1539,India,2009,885.01,879.71,611.11,728.56,104.37,13.08,16.82,11.64,106.34,0.08,16.27,567.02
1540,India,2010,943.02,937.47,642.97,771.78,118.03,10.78,23.08,14.30,108.74,0.11,19.46,599.02
1541,India,2011,1039.12,1034.00,701.25,828.16,117.56,9.35,32.22,17.14,131.70,0.83,23.95,646.97
1542,India,2012,1096.48,1091.84,787.13,893.45,96.25,10.07,33.14,19.94,115.78,2.10,27.43,707.83
1543,India,2013,1150.09,1146.14,847.97,924.93,66.31,10.65,33.31,22.48,131.98,3.43,30.01,744.52
1544,India,2014,1262.59,1262.02,949.93,1025.29,64.01,11.35,34.69,24.68,139.00,4.91,33.45,828.30
1545,India,2015,1317.25,1317.16,1006.55,1080.44,64.77,9.12,38.31,25.82,133.28,6.57,32.74,873.77
1546,India,2016,1400.54,1401.63,1073.60,1155.52,72.62,9.30,37.90,24.82,128.38,11.56,43.45,932.71
1547,India,2017,1469.56,1471.15,1115.24,1198.85,74.99,8.62,37.41,24.91,135.82,21.54,52.62,968.33
1548,India,2018,1575.14,1578.98,1198.86,1276.32,71.26,6.20,39.05,27.22,139.75,36.33,60.31,1034.81
1549,India,2019,1599.78,1603.48,1184.53,1257.05,67.47,5.05,45.16,29.67,162.02,46.27,63.31,1022.08
1550,India,2020,1561.18,1560.33,1125.22,1200.87,70.79,4.86,44.61,32.10,163.64,58.68,60.43,976.10

In [34]:
cleaned_data.to_csv('../Datasets/energy_data_clean.csv')